import { ProjectData, NodeData, EdgeData } from '../types';

/** Export full project JSON */
export function exportFullProject(project: ProjectData) {
  downloadJson(project, `${project.title || 'project'}_full.json`);
}

/** Export LangGraph-compatible state JSON */
export function exportLangGraphState(project: ProjectData) {
  // Transform characters
  const characters = project.characters.nodes.map((n) => {
    const relationships = project.characters.edges
      .filter((e) => e.source === n.id || e.target === n.id)
      .map((e) => {
        const targetId = e.source === n.id ? e.target : e.source;
        const targetNode = project.characters.nodes.find((nn) => nn.id === targetId);
        return {
          target: targetId,
          targetName: targetNode?.label || targetId,
          type: e.data?.relationType || e.label || '',
          desc: e.data?.description || '',
        };
      });
    return {
      id: n.id,
      name: n.data?.name || n.label,
      aliases: n.data?.aliases || [],
      gender: n.data?.gender || '',
      appearance: n.data?.appearance || '',
      personality: n.data?.personality || '',
      description: n.data?.description || '',
      attributes: n.data?.attributes || {},
      relationships,
    };
  });

  // Transform locations
  const locations = project.locations.nodes.map((n) => {
    const connections = project.locations.edges
      .filter((e) => e.source === n.id || e.target === n.id)
      .map((e) => {
        const targetId = e.source === n.id ? e.target : e.source;
        const targetNode = project.locations.nodes.find((nn) => nn.id === targetId);
        return {
          target: targetId,
          targetName: targetNode?.label || targetId,
          travelMethod: e.label || '通行方式',
          desc: e.data?.description || '',
        };
      });
    return {
      id: n.id,
      name: n.label,
      type: n.data?.locationType || '',
      description: n.data?.description || '',
      terrain: n.data?.terrain || '',
      connections,
    };
  });

  // Transform plot
  const checkpoints: Record<string, any> = {};
  project.plot.graph.nodes.forEach((n) => {
    checkpoints[n.id] = {
      id: n.id,
      label: n.label,
      player_info: n.data?.sceneDescription || '',
      hidden_info: n.data?.description || '',
      actions: n.data?.conditions || [],
    };
  });

  const transitions = project.plot.graph.edges.map((e) => ({
    from: e.source,
    to: e.target,
    label: e.label || '',
    trigger_condition: e.data?.conditionLogic || '',
    note: e.data?.description || '',
  }));

  const state = {
    script_title: project.title,
    world_setting: project.worldSetting.map((w) => ({
      title: w.title,
      content: w.content,
    })),
    characters,
    locations,
    plot: {
      initial_checkpoint: project.plot.initialCheckpoint,
      end_checkpoints: project.plot.endCheckpoints || [],
      checkpoints,
      transitions,
    },
    metadata: {
      exported_at: new Date().toISOString(),
      source: 'script-builder-platform',
    },
  };

  downloadJson(state, `${project.title || 'script'}_langgraph_state.json`);
}

/** Export Python initialization code */
export function exportPythonCode(project: ProjectData) {
  const state = buildLangGraphState(project);
  const pyCode = `# Generated by Script Builder Platform
# Copy this code into your LangGraph script

initial_state = ${JSON.stringify(state, null, 2).replace(/"/g, '\\"').replace(/\n/g, '\\n')}

# Usage:
# from your_langgraph_module import build_graph
# graph = build_graph()
# result = graph.invoke(initial_state)
`;

  // Actually, let's inline the JSON properly
  const jsonStr = JSON.stringify(state, null, 2);
  const finalCode = `# Generated by Script Builder Platform
# Copy this code into your LangGraph script

initial_state = ${jsonStr}

# Usage:
# from your_langgraph_module import build_graph
# graph = build_graph()
# result = graph.invoke(initial_state)
`;

  downloadText(finalCode, `${project.title || 'script'}_init.py`);
}

// --- helpers ---

function buildLangGraphState(project: ProjectData): any {
  const characters = project.characters.nodes.map((n) => {
    const relationships = project.characters.edges
      .filter((e) => e.source === n.id || e.target === n.id)
      .map((e) => {
        const targetId = e.source === n.id ? e.target : e.source;
        const targetNode = project.characters.nodes.find((nn) => nn.id === targetId);
        return {
          target: targetId,
          targetName: targetNode?.label || targetId,
          type: e.data?.relationType || e.label,
          desc: e.data?.description || '',
        };
      });
    return {
      id: n.id, name: n.data?.name || n.label,
      aliases: n.data?.aliases || [], gender: n.data?.gender || '',
      appearance: n.data?.appearance || '', personality: n.data?.personality || '',
      description: n.data?.description || '', attributes: n.data?.attributes || {},
      relationships,
    };
  });

  const locations = project.locations.nodes.map((n) => {
    const connections = project.locations.edges
      .filter((e) => e.source === n.id || e.target === n.id)
      .map((e) => {
        const targetId = e.source === n.id ? e.target : e.source;
        const targetNode = project.locations.nodes.find((nn) => nn.id === targetId);
        return { target: targetId, targetName: targetNode?.label || targetId, travelMethod: e.label, desc: e.data?.description || '' };
      });
    return {
      id: n.id, name: n.label, type: n.data?.locationType || '',
      description: n.data?.description || '', terrain: n.data?.terrain || '', connections,
    };
  });

  const checkpoints: Record<string, any> = {};
  project.plot.graph.nodes.forEach((n) => {
    checkpoints[n.id] = {
      id: n.id, label: n.label,
      player_info: n.data?.sceneDescription || '',
      hidden_info: n.data?.description || '',
      actions: n.data?.conditions || [],
    };
  });

  const transitions = project.plot.graph.edges.map((e) => ({
    from: e.source, to: e.target, label: e.label || '',
    trigger_condition: e.data?.conditionLogic || '', note: e.data?.description || '',
  }));

  return {
    script_title: project.title,
    world_setting: project.worldSetting.map((w) => ({ title: w.title, content: w.content })),
    characters, locations,
    plot: { initial_checkpoint: project.plot.initialCheckpoint, end_checkpoints: project.plot.endCheckpoints || [], checkpoints, transitions },
    metadata: { exported_at: new Date().toISOString(), source: 'script-builder-platform' },
  };
}

function downloadJson(data: any, filename: string) {
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
  downloadBlob(blob, filename);
}

function downloadText(text: string, filename: string) {
  const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
  downloadBlob(blob, filename);
}

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
